### ISSUE TITLE
#Linux 128 tickrate

### ISSUE THREAD

**Issue by zxhexa** [fbef0102/L4D1-Server4Dead#1]
[Outer Heaven: Ultimate] Tickrate_Enabler (tick 128 supported) 
This file does not have  '-frametime, -frametime_override' launch options

**Comment by fbef0102** [comment]
thanks report, 
removed ***-frametime 0.037 -frametime_override 0.037*** from description already

**Comment by dosergen** [comment]
[Outer Heaven: Ultimate] Tickrate_Enabler (tick 128 supported)
This file does not have 'sm_cvar tick_door_speed'

**Comment by dosergen** [comment]
sm_cvar tick_door_speed 
[SM] Unable to find cvar: tick_door_speed

**Comment by fbef0102** [comment]
cvar "tick_door_speed" is in this plugin "**TickrateFixes.smx**"
I already uploaded in linux and windows package
