### ISSUE TITLE
directory/appid is wrong

### ISSUE THREAD

**Issue by username-98** [fbef0102/L4D1-Server4Dead#2]
Step 3: after it says "Loading Steam API...OK.", type

force_install_dir ./l4d2/
login anonymous
app_update 222860 validate

should be :

Step 3: after it says "Loading Steam API...OK.", type

force_install_dir ./l4d1/
login anonymous
app_update 222840 validate

**Comment by fbef0102** [comment]
Nice catch, thanks

**Comment by username-98** [comment]
i was following your guide, and i was in a hurry, and i did copy paste the commands to install very fast, and i ended up downloading l4d2 files haha
